# Generated by Django 5.1.7 on 2025-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_spalva_animal_color_rename_vardas_animal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
