# Generated by Django 5.1.7 on 2025-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_animal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
