# Generated by Django 5.1.7 on 2025-04-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_animal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='has_isagai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Prieauglio atsivedimas', 'Prieauglio atsivedimas'), ('Gaišimas', 'Gaišimas'), ('Išvežimas', 'Išvežimas')], max_length=50),
        ),
    ]
