# Generated by Django 5.1.7 on 2025-03-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='name',
        ),
        migrations.AddField(
            model_name='animal',
            name='lytis',
            field=models.CharField(blank=True, choices=[('patinas', 'Patinas'), ('patelė', 'Patelė')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='numeris',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='spalva',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='svoris',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='vardas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
