# Generated by Django 5.1.7 on 2025-03-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_animal_birth_date_remove_animal_breed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='spalva',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='vardas',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='numeris',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='svoris',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='lytis',
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
