# Generated by Django 5.1.7 on 2025-03-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_animal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.CharField(blank=True, choices=[('grey', '1 - Grey'), ('brown', '2 - Brown'), ('black', '3 - Black'), ('white', '4 - White'), ('spotted', '5 - Spotted'), ('yellow', '6 - Yellow'), ('mottled', '7 - Mottled'), ('light_grey', '8 - Light Grey'), ('cream', '9 - Cream'), ('golden', '10 - Golden'), ('red', '11 - Red')], max_length=50, null=True),
        ),
    ]
